### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by xubangwu** [achalddave/segment-any-moving#10]
Hi, how can I could obtain the datasets called as DAVIS-Moving and YTVOS-Moving?

**Comment by nnanhuang** [comment]
Same question, have you figure it out ?

**Comment by achalddave** [comment]
Apologies for not getting to the initial issue here. The sequences for those videos are listed in the links below:

https://github.com/achalddave/segment-any-moving/blob/master/release/ytvos/moving_train_sequences.txt
https://github.com/achalddave/segment-any-moving/blob/master/release/ytvos/moving_val_sequences.txt
https://github.com/achalddave/segment-any-moving/blob/master/release/davis17/moving_train_sequences.txt
https://github.com/achalddave/segment-any-moving/blob/master/release/davis17/moving_val_sequences.txt
