### ISSUE TITLE
Detectron pytorch link incorrect

### ISSUE THREAD

**Issue by athun001** [achalddave/segment-any-moving#4]
detectron pytorch link: https://github.com/achalddave/segment-any-moving/blob/master/detectron_pytorch doesnt work. 
Will this link work: https://github.com/roytseng-tw/Detectron.pytorch

**Comment by achalddave** [comment]
Hm, where are you getting that first link from? The correct link should be: https://github.com/achalddave/segment-any-moving_detectron/

Let me know if you have any issues!

**Comment by achalddave** [comment]
I believe this should be fixed?
