### ISSUE TITLE
Updated Environment

### ISSUE THREAD

**Issue by MSiam** [achalddave/segment-any-moving#9]
I am trying to run the code with pytorch 1.9, CUDA 11.4 on a RTX A6000 GPU. Unfortunately I cant downgrade CUDA because that GPU doesnt support lower cuda versions. Can you please let me know if there is an updated version of the code that works with the latest torch.

I have tried to build on CUDA 9.0 with torch 0.4.0, and modifying the make.sh to have compute_86. The detectron_pytorch code you provide it shows unsupported gpu (which is expected) but doesnt give errors though. However when I execute this
```
python release/custom/run.py --model appearance --frames-dir DIR --output-dir OUTDIR --filename-format frameN
```
It gives this error
```
Traceback (most recent call last):
  File "tools/infer_simple.py", line 38, in <module>
    from modeling.model_builder import Generalized_RCNN
  File "/home/msiam/Code/segment-any-moving/detectron_pytorch/lib/modeling/model_builder.py", line 11, in <module>
    from model.roi_pooling.functions.roi_pool import RoIPoolFunction
  File "/home/msiam/Code/segment-any-moving/detectron_pytorch/lib/model/roi_pooling/functions/roi_pool.py", line 3, in <module>
    from .._ext import roi_pooling
  File "/home/msiam/Code/segment-any-moving/detectron_pytorch/lib/model/roi_pooling/_ext/roi_pooling/__init__.py", line 3, in <module>
    from ._roi_pooling import lib as _lib, ffi as _ffi
ImportError: /home/msiam/Code/segment-any-moving/detectron_pytorch/lib/model/roi_pooling/_ext/roi_pooling/_roi_pooling.so: undefined symbol: __cudaRegisterFatBinaryEnd
```
Anyway to hack it to work.

Thanks for your help in advance.

**Comment by MSiam** [comment]
I made it work on a 1080Ti with older CUDA version.

**Comment by Coronal-Halo** [comment]
Which CUDA version did you use? How did you solve this issue exactly?
